name: exemplo_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # Verifique a vers達o mais recente
  firebase_auth: ^5.0.0    # Altere para a vers達o mais recente
  cloud_firestore: ^5.4.4   # Altere para a vers達o mais recente
  geolocator: ^13.0.1    # Ou a vers達o mais recente
  local_auth: ^2.3.0       # Para biometria
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
